name: firebase_authentication_tutorial
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  #Firebase
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  #  flutter_svg:
  velocity_x:
  get:
  cloud_firestore:
  google_sign_in: ^4.5.6
  table_calendar: ^2.3.3
  datetime_picker_formfield: ^1.0.0
  flutter_datetime_picker:
  date_format: ^1.0.9
  #  timetable: ^0.2.9
  time_machine: ^0.9.16
  http: ^0.12.0+4
  flutter_riverpod: ^0.11.2
  firebase_helpers:
  shared_preferences: ^0.5.12+4
  google_fonts: ^1.1.0
  firebase_database:
  flutter_form_builder: ^4.0.1
  provider: ^4.3.2+1
  flutter_facebook_login: ^3.0.0
  intl: '^0.16.1'
  dataclass: ^0.5.0+1

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  date_range_picker:
    git:
      url: https://github.com/LempereurBenjamin/date_range_picker


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true



  assets:
    - assets/images/strawberries.jpg
    - assets/images/listening_compare.png
    - assets/images/facebook.png
    - assets/images/twitter.jpg
    -  assets/images/instagram.jpg
